/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { BMC, BMCInterface } from "../BMC";

const _abi = [
  {
    inputs: [],
    name: "getBtpAddress",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_to",
        type: "string",
      },
      {
        internalType: "bool",
        name: "_response",
        type: "bool",
      },
    ],
    name: "getFee",
    outputs: [
      {
        internalType: "uint256",
        name: "_fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNetworkAddress",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNetworkSn",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_to",
        type: "string",
      },
      {
        internalType: "string",
        name: "_svc",
        type: "string",
      },
      {
        internalType: "int256",
        name: "_sn",
        type: "int256",
      },
      {
        internalType: "bytes",
        name: "_msg",
        type: "bytes",
      },
    ],
    name: "sendMessage",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class BMC__factory {
  static readonly abi = _abi;
  static createInterface(): BMCInterface {
    return new Interface(_abi) as BMCInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BMC {
    return new Contract(address, _abi, runner) as unknown as BMC;
  }
}
