/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BMC__factory } from "./BMC__factory";
export { CallService__factory } from "./CallService__factory";
