/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BMC } from "./BMC";
export type { CallService } from "./CallService";
export * as factories from "./factories";
export { BMC__factory } from "./factories/BMC__factory";
export { CallService__factory } from "./factories/CallService__factory";
